// npm run demo: headline failure + full scenario x agent-mode matrix -> report.md
import { writeFileSync } from 'node:fs';
import { BUGS, type Bug } from './agent';
import { passK, runScenario, scenarios } from './contracts';

const K = 10;
const byId = (id: string) => scenarios.find((s) => s.id === id)!;

function show(title: string, bugs: Bug[]) {
  const r = runScenario(byId('cancel_api_error'), bugs);
  const out = [`\n=== ${title} ===`, `agent said: "${r.reply}"`];
  for (const c of r.checks) out.push(`  ${c.pass ? 'PASS' : 'FAIL'} ${c.name}${c.pass ? '' : `\n       -> ${c.detail}`}`);
  out.push('  call log:', ...r.log.map((c, i) => `    #${i} ${c.tool} ${JSON.stringify(c.args)} -> ${c.ok ? 'ok' : `ERROR ${c.error}`}`));
  out.push(`  DB subscriptions[C-1]: ${JSON.stringify(r.db.subscriptions['C-1'])}`);
  out.push(`  VERDICT: ${r.failed.length ? `FAIL (${r.failed.join(', ')})` : 'PASS'}`);
  return out.join('\n');
}

const headline = [
  show('cancel_api_error / agent mode: claims_success_on_error', ['claims_success_on_error']),
  show('cancel_api_error / agent mode: correct', []),
].join('\n');
console.log(headline);

const modes: (Bug | 'correct')[] = ['correct', ...BUGS];
const rows = scenarios.map((s) => `| ${s.id} | ${modes.map((m) => {
  const r = passK(s, m === 'correct' ? [] : [m], K);
  return r.passK ? `PASS ${r.passes}/${K}` : `**FAIL** ${r.passes}/${K}<br>${r.failed.join(', ')}`;
}).join(' | ')} |`);

const table = [`| scenario | ${modes.join(' | ')} |`, `|---|${modes.map(() => '---').join('|')}|`, ...rows].join('\n');
const report = `# Agent Contract Test Report

Agent under test: **simulated** offline scripted agent (no LLM). Each cell runs the scenario k=${K} times
on a fresh backend; PASS only if all k runs pass (pass^k). \`n/${K}\` = runs that passed. Failing cells list the violated checks.

## Headline: agent says "cancelled", API said error

\`\`\`text${headline}
\`\`\`

## Scenario x agent mode

${table}

Generated by \`npm run demo\`.
`;
writeFileSync('report.md', report);
console.log(`\n${table}\n\nwrote report.md`);
